services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: glpi:nginx
    hostname: web
    container_name: glpi-nginx
    ports:
      - "80:80"
    depends_on:
      - php
    volumes:
      - ./glpi:/var/www/glpi
    restart: unless-stopped
    user: root
    networks:
      - glpinet

  php:
    build:
      context: ./php-fpm
      dockerfile: Dockerfile
    image: glpi:fpm
    hostname: glpi
    container_name: glpi-fpm
    expose:
      - 9000
    depends_on:
      - db
    volumes:
      - ./glpi:/var/www/glpi
    restart: unless-stopped
    user: root
    networks:
      - glpinet

  db:
    image: mysql:lts
    hostname: mysql
    container_name: glpi-db
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    expose:
      - 3306
    ports:
      - "6033:3306"
    volumes:
      - ./dbdata:/var/lib/mysql
    restart: unless-stopped
    user: root
    networks:
      - glpinet

networks:
  glpinet:
