services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: ${GIT_REPO_ENDPOINT}/glpi-nginx:latest
    hostname: web
    container_name: glpi-nginx
    environment:
      - FASTCGI_PASS=${FASTCGI_PASS}
    ports:
      - "80:80"
    depends_on:
      php:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost/index.php || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 5
    networks:
      - glpinet

  php:
    build:
      context: ./php-fpm
      dockerfile: Dockerfile
    image: ${GIT_REPO_ENDPOINT}/glpi-php-fpm:latest
    hostname: glpi
    container_name: glpi-fpm
    environment:
      - GLPI_DB_HOST=${GLPI_DB_HOST}
      - GLPI_DB_PORT=${GLPI_DB_PORT}
      - GLPI_DB_DATABASE=${GLPI_DB_DATABASE}
      - GLPI_DB_USER=${GLPI_DB_USER}
      - GLPI_DB_PASSWORD=${GLPI_DB_PASSWORD}
      - GLPI_ADMIN_USER=${GLPI_ADMIN_USER}
      - GLPI_VERSION=${GLPI_VERSION}
      - GLPI_SAML_VERSION=${GLPI_SAML_VERSION}
    expose:
      - 9000
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - glpi:/glpi-data:rw
    restart: unless-stopped
    networks:
      - glpinet
    healthcheck:
      test: ["CMD-SHELL", "php-fpm -t || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 5

  db:
    image: mysql:lts
    hostname: mysql
    container_name: glpi-db
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${GLPI_DB_DATABASE}
      - MYSQL_USER=${GLPI_DB_USER}
      - MYSQL_PASSWORD=${GLPI_DB_PASSWORD}
    expose:
      - 3306
    ports:
      - "6033:3306"
    volumes:
      - dbdata:/var/lib/mysql:rw
      - ./mysql-init.sql:/docker-entrypoint-initdb.d/mysql-init.sql
    restart: always
    networks:
      - glpinet
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  glpinet:

volumes:
  dbdata:
  glpi:
